// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: example_project

#ifndef _EXAMPLE_PROJECT_UI_H
#define _EXAMPLE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_date;
void ui_event_logo_button(lv_event_t * e);
extern lv_obj_t * ui_logo_button;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_sls_logo_png);    // assets\sls_logo.png


LV_FONT_DECLARE(ui_font_clock_60);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
