#include <Arduino.h>
#include "ui/lv_setup.h"
#include "ui/ui.h"
#include "pin_config.h"

void setup()
{
  lv_begin(); // Initialize lvgl with display and touch
  ui_init();  // Initialize UI generated by Square Line
}

void loop()
{
  lv_handler(); // Updates UI
}