#include <Arduino.h>
#include "ui/lv_setup.h"
#include "ui/ui.h"
#include "pin_config.h"
#include "time_func.h"

void setup()
{
  lv_begin();  // Initialize lvgl with display and touch
  ui_init();   // Initialize UI generated by Square Line
  time_init(); // Initialize time and date from compiler
}

void loop()
{
  lv_handler();  // Updates UI
  update_time(); // Updates time and date on UI
}